[WIP] 0.0.1
theforeman/hammer-cli-foreman-leapp pull request #2
Opened 2020-04-27 06:44 UTC by stejskalleos

TODO

2020-04-27 07:38 UTC, adamruzicka requested changes

2020-04-27 07:38 UTC, adamruzicka commented on README.md
> +|            foreman_ansible | 1.0.0 |
`s/ansible/leapp` and correct the versions

2020-04-27 07:38 UTC, adamruzicka commented on lib/hammer_cli_foreman_leapp.rb
> +    'Manage Leapp preupgrade_reports',
I guess this is what gets displayed to the user, right? If that is the case, then we should probably drop the underscore from preupgrade_report

2020-04-27 07:38 UTC, adamruzicka commented on lib/hammer_cli_foreman_leapp.rb
> +    'preupgrade_reports',
From what I've seen, hammer usually uses kebab-case

2020-04-27 07:38 UTC, adamruzicka commented on lib/hammer_cli_foreman_leapp/preupgrade_reports.rb
> +      build_options
This is a bit misleading. `preupgrade_reports list` shows columns `id` and `job_invocation_id`, however `preupgrade_reports --id $ID` expects `$ID` to be a job invocation id

2020-04-27 07:38 UTC, adamruzicka commented on lib/hammer_cli_foreman_leapp/preupgrade_reports.rb
> +        end
This only gets shown in info, right? So maybe it should live in that subcommand and extend list command's output with additional fields?

2020-04-28 12:20 UTC, ofedoren approved these changes
Looks good so far. Haven't tested functionality though... I've broken my dev env while trying to upgrade to nightlies... But if it works for someone, here's my ACK.

2020-04-28 12:20 UTC, ofedoren commented on README.md
> +| hammer_cli_foreman_leapp | 1.0.0 |
:heart: I'd like to see such approach in all of the hammer plugins. Thanks for being precise! Just don't forget that current hammer-cli-foreman-leapp version is 0.0.1.

2020-04-28 12:20 UTC, ofedoren commented on README.md
> +    hammer preupgrade_reports --help
Should be `hammer preupgrade-reports --help`

2020-04-28 12:24 UTC, ofedoren commented
One addition: after I took a look at the foreman_leapp part, I've noticed that the API doc for the show endpoint has changed. Not sure now if hammer info command will work after cache is updated with that change... Needs to be tested. Hopefully I will manage to re-create dev env to test it in reasonable future.

2020-04-28 13:43 UTC, stejskalleos commented on README.md
> +| hammer_cli_foreman_leapp | 1.0.0 |
Thanks! About the version, I'm will update versions when plugins be ready to release.

2020-04-29 05:46 UTC, stejskalleos commented
> One addition: after I took a look at the foreman_leapp part, I've noticed that the API doc for the show endpoint has changed. Not sure now if hammer info command will work after cache is updated with that change... Needs to be tested. Hopefully I will manage to re-create dev env to test it in reasonable future.

Yeah for the Leapp API you need to have Leapp branch https://github.com/oamg/foreman_leapp/pull/51

2020-05-04 14:36 UTC, stejskalleos commented
Because https://github.com/oamg/foreman_leapp/pull/51 took longer than I was expecting and we need to start with packaging, I removed actions from this plugin so we could release first version and start working on packaging.

2020-05-04 14:42 UTC, ofedoren approved these changes
LGTM :)

2020-05-04 14:46 UTC, merged